name: via_cep_contacts_projects_uex
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  chuck_interceptor: ^2.0.9
  connectivity_plus: ^5.0.2
  dio: ^5.4.1
  equatable: ^2.0.5
  firebase_core: ^2.25.4
  firebase_crashlytics: ^3.4.15
  flutter_dotenv: ^5.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.5
  get_it: ^7.6.7
  hive: ^2.2.3
  http_parser: ^4.0.2
  intl: ^0.18.0
  pretty_dio_logger: ^1.3.1
  path_provider: ^2.1.2
  
dev_dependencies:
  faker: ^2.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  test_api: ^0.6.1

flutter:
  uses-material-design: true
  assets:
    - lib/shared/presentation/assets/images/

